# 📚 GAME CONTENT LIBRARY (PHASE 19 - EXPANDED)

GAME_DATA = {
    "tod_truth": [
        # --- ICEBREAKERS ---
        "What is the last lie you told?", 
        "What is your biggest fear?",
        "Who is your secret crush?",
        "What is your most embarrassing moment?", 
        "Have you ever cheated on a test?",
        "What is the worst gift you ever received?", 
        "What is your biggest regret?",
        "When was the last time you cried?", 
        "What is a secret you've never told anyone?",
        "If you could switch lives with one person, who would it be?",
        "What is a habit you want to break?", 
        "Who is the most annoying person you know?",
        "What is your biggest insecurity?",
        "What is the weirdest dream you've ever had?",
        "Have you ever stalked someone on social media?",
	"Do you have any fake account?",
        "What is the pettiest thing you have ever done?",
        "If you were invisible for a day, what would you do?",
        "What is the worst date you've ever been on?",
        "Have you(someone) ever ghosted someone(you)?",
        "What is one thing you wish you could change about yourself?",
        "Who is the last person you searched on Instagram?",
        "Have you ever broken the law?",
        "What is the most expensive thing you've bought and regretted?",
        "If you had to marry the last person you texted, who would it be?",
        "What is your guilty pleasure?",
        
        # --- DEEP / VIBE CHECK ---
        "Do you believe in soulmates?",
        "What is your biggest deal-breaker in a relationship?",
        "Would you forgive a cheater?",
        "What is the happiest memory of your childhood?",
        "Do you think you are a good person?",
        "What is one thing you want to achieve before you die?",
        "Do you believe in ghosts or aliens?",
	"Saddest moment of your life?",
        "What is the hardest lesson you've had to learn?",
        "If you could apologize to one person from your past, who would it be?",
        "Are you happy with where you are in life right now?",
        "What is your definition of love?",
        "Have you ever fallen in love with a friend?",
        "What is something you are sensitive about?",
        "Do you trust people easily?",
        "What is your biggest fear about the future?",
        # --- FLIRTY & SPICY (User Added) ---
        "What is your love language?",
        "What is your biggest fantasy?",
        "What is one thing you struggle with in relationships?",
        "What was your first impression of me (based on this chat)?",
        "What is the first thing that attracts you to someone?",
        "What usually gets you in a romantic mood?",
        "Have you ever turned down a sexual opportunity and regretted it?",
        "Have you ever hooked up with someone you regret?",
        "At what age did you first learn about sex?",
        "Have you ever sexted?",
        "What is the sexiest song you've ever heard?",
        "What is the sexiest movie scene you've ever watched?",
        "At what age did you watch your first adult video?",
        "Have you ever hit on a random attractive stranger?",
        "Have you ever tried to get back together with an ex?",
        "What is a romantic act that you think is overrated?",
        "What romantic activity do you think is underrated?",
        "Can you fall asleep while cuddling/kissing?",
        "Kissing on the first date: Yay or Nay?",
        "Public Displays of Affection (PDA): Yay or Nay?",
        "What is your favorite body part to be kissed?",
        "Where do you like to leave/get a hickey?",
        "What is the sexiest outfit someone can wear?",
        "How old were you when you had your first kiss?",
        "What do you think is the sexiest part of the opposite gender's body?",
        "What do you think is the sexiest part of YOUR body?"
    ],

    "tod_dare": [
        # --- DIGITAL DARES (Safe for Chat) ---
        "Send a voice note singing 'Happy Birthday' to me.", 
        "Send the last photo which you took (no cheating!).",
        "Send me picture of your nose",
	"Show me your Nails", 
        "Send a sticker that describes your mood right now.",
        "Send me voice note of Count 10 to 1 (quickest you can!)",
        "Send me 5 last used Emoji", 
	"Send a voice note blowing a kiss.",
        "Send a photo of just your lips.",
        "Describe your ideal first date in detail.",
        "Send a voice note whispering 'I like you'.",
        "Type the most flirty text you can think of.",
        "Send a selfie biting your lip.",
        "Describe what you are wearing right now.",
        "Send a voice note listing 3 of your turn-ons.",
        "Send a photo of your eyes.",
        "Rate my 'vibes' from 1 to 10 and explain why.",
        "Send a voice note singing a romantic song (just one line).",
        "Type a fake breakup text to me.",
        "Send the 5th photo in your gallery (no cheating, even if it's risky).",
        "Tell me the story of your first kiss.",
        "Show me your Ear",
        "Send a screenshot of your home screen.",
        "Send me pic of your eyes",
        "sing a song and send voice note",
        "Send a voice note imitating a celebrity.",
        "Send the last sms you got.",
        "Show your Lower Lip.",
        "Send a voice note of weird laugh.",
        "Send a photo of the view from your window.",
        "Tell me a joke in a voice note.",
        "Bark like a Cat in a voice note.",
        "Send a screenshot of your last Google search.",
        "Send a voice note saying something in a different accent.",
        "Send a pic of your palm",
        "Go to your music player, shuffle, and send the first song that plays.",
        "Send a voice note yelling 'I LOVE THIS BOT!'",
        "Describe what you are wearing right now.",
        "Send a screenshot of your most used emojis.",
        "Record yourself saying a tongue twister-Red Lorry Yellow Lorry three times fast."
    ],

    "wyr": [
        # --- CLASSIC & SUPERPOWERS ---
        ("Have infinite money", "Have infinite love"),
        ("Be invisible", "Be able to fly"), 
        ("Always be cold", "Always be hot"),
        ("Have unlimited money", "Have unlimited time"), 
        ("Know how you die", "Know when you die"),
        ("Explore Space", "Explore the Ocean"), 
        ("Talk to animals", "Speak all languages"),
        ("Be a famous movie star", "Be a brilliant scientist"),
        ("Never use social media again", "Never watch movies again"),
        ("Lose your phone", "Lose your wallet"),
        ("Be the smartest person in the room", "Be the funniest person in the room"),
        ("Have a rewind button", "Have a pause button"),
        ("Be able to read minds", "Be able to see the future"),
        ("Be feared by all", "Be loved by all"),
        ("Never have to sleep", "Never have to eat"),
        ("Only be able to whisper", "Only be able to shout"),
        ("Have universal respect", "Have unlimited power"),
        ("Live in a treehouse", "Live in a cave"),
        ("Be 4'5\" tall", "Be 7'7\" tall"),

        # --- LOVE & RELATIONSHIPS ---
        ("Date someone 10 years older", "Date someone 5 years younger"),
        ("Have amazing sex but no conversation", "Have amazing conversation but bad sex"),
        ("Kiss in the rain", "Kiss by a fireplace"),
        ("Be the heartbreaker", "Have your heart broken"),
        ("Have a partner who is too clingy", "Have a partner who is too distant"),
        ("Forgive a cheater", "Forgive a liar"),
        ("Lights on", "Lights off"),
        ("Morning cuddles", "Late night deep talks"),
        ("Date a famous celebrity", "Date a regular person who adores you"),
        ("Find true love but be poor", "Stay single but be a billionaire"),
        ("Have a one-night stand", "Have a 'friends with benefits' relationship"),
        ("Your partner looks through your phone", "You look through your partner's phone"),
        ("Have no partner", "Have 3 partners"),
        ("Stay a virgin forever", "Stay single forever"),
        ("Kiss in public", "Kiss in a classroom"),
        ("Marry your first love", "Marry your celebrity crush"),
        ("Your partner is rich but boring", "Your partner is broke but hilarious"),

        # --- LIFESTYLE & SITUATIONAL (Fixed & New) ---
        ("Live in the past", "Live in the future"),
        ("Give up music", "Give up movies"),
        ("Have nosy neighbors", "Have noisy neighbors"),
        ("Be an average person in the present", "Be a King/Queen 1000 years ago"),
        ("Find true love today", "Win the lottery next year"),
        ("Have no taste", "Have no smell"),
        ("Always say everything on your mind", "Never be able to speak again"),
        ("Go 10 years into the past", "Get $10 million today"), 
        ("Visit the mountains", "Visit the beach"),
        ("Hang out at night", "Hang out in the evening"),
        ("Sing in public", "Dance in public"),
        ("Watch the sunset", "Watch the sunrise"),
        ("Be overdressed", "Be underdressed"),
        ("Have no internet for a month", "Have no hot water for a month"),
        ("Be famous on Instagram", "Be famous on YouTube"),
        ("Fight 100 duck-sized horses", "Fight 1 horse-sized duck"),
        ("Always have a stone in your shoe", "Always have a slow internet connection"),

        # --- DARK & DEEP ---
        ("Save 100 strangers", "Save 1 family member"),
        ("Know all the world's secrets", "Live in blissful ignorance"),
        ("Restart your life at age 10", "Fast forward to age 40 with $50M"),
        ("Be in jail for 5 years", "Be in a coma for 10 years"),
        ("Die happy in 5 years", "Die miserable in 100 years"),
        ("Accidentally send a sext to your boss", "Accidentally send a sext to your mom"),
        ("Have everyone know your search history", "Have everyone know your financial status"),
        
        # --- CRAZY & FUNNY ---
        ("Have fingers as long as legs", "Have legs as long as fingers"),
        ("Sweat mayonnaise", "Cry orange juice"),
        ("Have a head the size of a tennis ball", "Have a head the size of a watermelon"),
        ("Talk like Yoda", "Walk like a penguin"),
        ("Have a constant itch", "Have a constant hiccup"),
        ("Use sandpaper as toilet paper", "Use hot sauce as eye drops"),
		# --- CRAZY, CLINGY & 18+ (Patch) ---
        ("Let me track your live location 24/7", "Let me read your chats every night"),
        ("Quickie in a car", "Quickie in an elevator"),
        ("Swallow", "Spit"),
	
	# --- KINKY & FANTASY (Roleplay/Supernatural) ---
        ("Roleplay as a student & teacher", "Roleplay: Doctor & Patient"),
        ("like to have partner like vampire (biting involved)", "Like a werewolf (scratching involved)"),
        ("Be hypnotized to do anything I say", "Hypnotize me to do anything you say"),
        ("Have a clone of yourself for a threesome", "Have a clone of me for a threesome"),
        ("Do Romance in zero gravity (floating)", "Do it underwater (breathing magic)"),
        ("Be my personal servant in a fantasy kingdom", "Be the ruler who owns me"),
       
        ("Be handcuffed", "Be blindfolded"),
        ("I tie you up", "You tie me up"),
        ("Be teased with an ice cube while blindfolded", "Be teased with ice cream while handcuffed"),
        
	# --- CLINGY & OBSESSIVE (Crazy but Safe-ish) ---
        ("Have a joint social media account", "Have a joint bank account"),
        ("Text me every 10 minutes", "Call me every hour"),
        ("Tell me every thought you have", "Let me watch you 24*7"),
        ("Move in together after 1 week", "Get married after 1 month"),
        ("Let me brush your hair", "Let me feed you dinner"),
        ("Be attacked by a zombie", "Be attacked by a shark")
    ]
}

